// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3NSGjph1DsI6T_pgc_EaNeCqY5Yt1sZ8',
    appId: '1:433039788011:web:db738de9f549bf1070bbae',
    messagingSenderId: '433039788011',
    projectId: 'iucclub',
    authDomain: 'iucclub.firebaseapp.com',
    storageBucket: 'iucclub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqEExkXEzPp8hgeLOCNiVB43ZV9--EDBY',
    appId: '1:433039788011:android:2ecd2884a5d1c17870bbae',
    messagingSenderId: '433039788011',
    projectId: 'iucclub',
    storageBucket: 'iucclub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqZdJ5PtgwLscJAdXa_B03ZaiwDXAQKo8',
    appId: '1:433039788011:ios:d32060d3168d5e5070bbae',
    messagingSenderId: '433039788011',
    projectId: 'iucclub',
    storageBucket: 'iucclub.firebasestorage.app',
    iosBundleId: 'com.example.iucClub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqZdJ5PtgwLscJAdXa_B03ZaiwDXAQKo8',
    appId: '1:433039788011:ios:d32060d3168d5e5070bbae',
    messagingSenderId: '433039788011',
    projectId: 'iucclub',
    storageBucket: 'iucclub.firebasestorage.app',
    iosBundleId: 'com.example.iucClub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3NSGjph1DsI6T_pgc_EaNeCqY5Yt1sZ8',
    appId: '1:433039788011:web:878fac04ff04aa0f70bbae',
    messagingSenderId: '433039788011',
    projectId: 'iucclub',
    authDomain: 'iucclub.firebaseapp.com',
    storageBucket: 'iucclub.firebasestorage.app',
  );
}
